# Build Step
FROM node:10

ENV PORT=3000
ENV DATABASE_HOST=localhost
ENV DATABASE_PORT=5432
ENV DATABASE_USER=apps
ENV DATABASE_PASSWORD=bitcapital
ENV BITCAPITAL_CLIENT_URL=https://testnet.btcore.app
ENV BITCAPITAL_CLIENT_ID=p2p-lending-sample
ENV BITCAPITAL_CLIENT_SECRET=91c29bca-3cf3-4324-ba7a-0eb933a4b01b
ENV BITCAPITAL_CLIENT_DOMAIN=3ed7d74e-fe48-4192-b044-86592ae9a08f
ENV BITCAPITAL_MEDIATOR_EMAIL=fabio@bitcapital.com.br
ENV BITCAPITAL_MEDIATOR_PASSWORD=fabiofabio
ENV PAGINATION_LIMIT=50
ENV LOCAL_ASSET_CODE=BRHD

RUN mkdir /home/p2p-lending-sample

WORKDIR /home/p2p-lending-sample

COPY package.json .

RUN yarn install

COPY . .

EXPOSE 3000

CMD [ "yarn", "start"]